adj1 = input("enter an adjective: ")
adj2 = input("enter an adjective: ")
typb1 = input("enter type of bird: ")
rih = input("enter a room in a house: ")
ver1 = inout("enter a verb: ")
rn1 + input("enter relative's name: ")
n1 = input( "enter a noun: ")
liq = input("enter a liquid: ")
ver2 = input(" enter a verb ending in -ing:  ")
pob = input("enter part of the body (plural): ")
pln = input("enter plural noun: ")
ver3 = input("enter verb ending in -ing: ")
n2 = input("enter a noun")